abbr -a b " bat"
abbr -a bn " bat --paging=never"
abbr -a bd " bd"
abbr -a btm " btm --disable_click --process_memory_as_value --enable_cache_memory "
abbr -a c " cdh"
abbr -a cd " cd"
abbr -a cdd " cd ../"
abbr -a d " dejima"
abbr -a fdu " du -hs (find . -maxdepth 1 -type d | fzf)"
abbr -a fcd " fcd"
abbr -a fdiff " fzf_git_diff"
abbr -a fkill " ps | fzf | awk '{print \$1}' | xargs kill -9"
abbr -a glow " glow"
abbr -a gpwd " git rev-parse --show-prefix"
abbr -a l " lazygit"
abbr -a ll " gls --color --group-directories-first -AlhFX"
abbr -a ls " gls --color"
abbr -a mermaid " fd -e md | fzf | xargs -I {} podman run --userns keep-id --user (id -u) --rm -v "$PWD":/data:z ghcr.io/mermaid-js/mermaid-cli/mermaid-cli -s 8 -i {} -o output.png"
abbr -a marp " fd -e md | fzf | xargs -I {}  podman run --rm --init --mount type=bind,source=(pwd),target=/home/marp/app/ docker.io/marpteam/marp-cli {} --pdf"
abbr -a n " nvim"
abbr -a nn " nvim -c ':tabnew term://fish | stopinsert | tabmove 0 | tabnext'"
abbr -a tf " tail -f"
abbr -a z " z"
abbr -a zi " zi"

