# initial settings
unbind C-b
bind C-Space send-prefix
set-option -g prefix C-Space
set-option -g escape-time 0
set-option -g focus-events on
set-option -g mouse on
set-option -g mode-keys vi
set-option -g history-limit 30000
set-option -g extended-keys on
set-option -g extended-keys-format csi-u

# reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# show popup window
POPUP_NAME=popup
POPUP_SIZE=98%
bind q if-shell -F '#{==:#{session_name},popup}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -w $POPUP_SIZE -h $POPUP_SIZE -E 'tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME'
}

# kill non-focused panes
bind e confirm-before -p "kill non-focused panes? (y/n)"  "kill-pane -a"

# send pane to other tab
bind t command-prompt -p "send pane to:"  "join-pane -t :'%%'"

# split window
bind -r v split-window -h -c '#{pane_current_path}'
bind -r s split-window -v -c '#{pane_current_path}'

# vim-like pane switching
bind -r C-k select-pane -U
bind -r C-j select-pane -D
bind -r C-h select-pane -L
bind -r C-l select-pane -R
unbind l

# resize pane
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# vim-like copy mode
bind C-g copy-mode
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
bind -T copy-mode-vi 'f' send-key ?
bind P paste-buffer

# move window
bind -n C-Left previous-window
bind -n C-Right next-window

# swap window
bind -n S-Left swap-window -t -1 \; previous-window
bind -n S-Right swap-window -t +1 \; next-window

# select window from list
bind w choose-tree -w

# allow the title bar to adapt to whatever host you connect to
set-option -g set-titles on
set-option -g set-titles-string "#T"
set-option -g renumber-windows on

#UI
set-option -g default-terminal "xterm-256color"
set-option -g terminal-overrides ",xterm-256color:RGB"
set-option -g status-interval 1
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g pane-border-indicators "both"
set-option -g pane-border-lines "double"
set-option -g pane-scrollbars "modal"
set-option -g pane-border-style 'fg=colour238'
set-option -g pane-active-border-style 'fg=colour39,bold'


# status lineの設定
set-option -g status-position "top"
set-option -g status-justify "absolute-centre"
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"
set-option -g status-left "#[fg=colour255,bg=colour241] [#S:#{session_windows}] "
set-option -g status-right "#[fg=colour255,bg=colour241] [#{server_sessions}] #h | %m/%d %H:%M:%S "
set-option -g window-status-separator ""
set-window-option -g window-status-format "[#I:#{window_panes}] #{?window_bell_flag, 󱅫} #W@#{b:pane_current_path} "
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold]#{?window_zoomed_flag,#[bg=colour196],}#{?client_prefix,#[bg=colour208],} [#I:#{window_panes}] #W@#{b:pane_current_path} "
set-option -g window-status-bell-style "bold"
